# Generated by Django 5.1.2 on 2024-11-22 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='authority_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Mid_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Area', models.CharField(blank=True, max_length=100, null=True)),
                ('Mail', models.CharField(blank=True, max_length=100, null=True)),
                ('Pincode', models.IntegerField(blank=True, null=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('Panchayath_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Profile', models.FileField(blank=True, null=True, upload_to='profile/')),
                ('Phone_no', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='chat_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Login_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=100, null=True)),
                ('Password', models.CharField(blank=True, max_length=100, null=True)),
                ('Type', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='staff_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Mid_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Mail', models.CharField(blank=True, max_length=100, null=True)),
                ('Pincode', models.IntegerField(blank=True, null=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('Profile', models.FileField(blank=True, null=True, upload_to='profile/')),
                ('Phone_no', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='time_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.CharField(blank=True, max_length=100, null=True)),
                ('Time', models.TimeField(blank=True, null=True)),
                ('Date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Mid_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Mail', models.CharField(blank=True, max_length=100, null=True)),
                ('Pincode', models.IntegerField(blank=True, null=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('Consumer_no', models.CharField(blank=True, max_length=100, null=True)),
                ('Profile', models.FileField(blank=True, null=True, upload_to='profile/')),
                ('Phone_no', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='report_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Consumer_no', models.CharField(blank=True, max_length=100, null=True)),
                ('Complaint_no', models.CharField(blank=True, max_length=100, null=True)),
                ('Upload_photo', models.FileField(blank=True, null=True, upload_to='photo/')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AquaFlowApp.staff_model')),
            ],
        ),
        migrations.CreateModel(
            name='assignedwork_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.CharField(blank=True, max_length=100, null=True)),
                ('Work', models.CharField(blank=True, max_length=100, null=True)),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AquaFlowApp.staff_model')),
            ],
        ),
        migrations.CreateModel(
            name='area_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.CharField(blank=True, max_length=100, null=True)),
                ('AUTHORITY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AquaFlowApp.authority_model')),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AquaFlowApp.staff_model')),
            ],
        ),
        migrations.CreateModel(
            name='reading_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Current_reading', models.IntegerField(blank=True, null=True)),
                ('Total_usage', models.IntegerField(blank=True, null=True)),
                ('Fixed_charge', models.IntegerField(blank=True, null=True)),
                ('Advance', models.IntegerField(blank=True, null=True)),
                ('Prior_obligation', models.IntegerField(blank=True, null=True)),
                ('Fine', models.IntegerField(blank=True, null=True)),
                ('Total_amount', models.IntegerField(blank=True, null=True)),
                ('STAFF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AquaFlowApp.staff_model')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AquaFlowApp.user_model')),
            ],
        ),
        migrations.CreateModel(
            name='feedback_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback', models.CharField(blank=True, max_length=100, null=True)),
                ('Rating', models.FloatField(blank=True, null=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AquaFlowApp.user_model')),
            ],
        ),
        migrations.CreateModel(
            name='complaints_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaints', models.CharField(blank=True, max_length=100, null=True)),
                ('Reply', models.FileField(blank=True, null=True, upload_to='')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AquaFlowApp.user_model')),
            ],
        ),
        migrations.CreateModel(
            name='bill_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Payment_status', models.CharField(blank=True, max_length=100, null=True)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Due_date', models.DateTimeField(auto_now_add=True)),
                ('READING', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AquaFlowApp.reading_model')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AquaFlowApp.user_model')),
            ],
        ),
        migrations.CreateModel(
            name='application_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Application_no', models.IntegerField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=100, null=True)),
                ('Panchayath_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('Phone_no', models.IntegerField(blank=True, null=True)),
                ('Family_members', models.IntegerField(blank=True, null=True)),
                ('Adhar_no', models.IntegerField(blank=True, null=True)),
                ('Rationcard', models.CharField(blank=True, max_length=100, null=True)),
                ('Neighbourconsumer_no', models.IntegerField(blank=True, null=True)),
                ('Cast', models.CharField(blank=True, max_length=100, null=True)),
                ('Adhar_photo', models.FileField(blank=True, null=True, upload_to='photo/')),
                ('Rationcard_photo', models.FileField(blank=True, null=True, upload_to='photo/')),
                ('Ownershipcertificate_photo', models.FileField(blank=True, null=True, upload_to='photo/')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AquaFlowApp.user_model')),
            ],
        ),
    ]
