# Generated by Django 5.1.2 on 2024-11-22 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AquaFlowApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area_model',
            name='AUTHORITY',
        ),
        migrations.RemoveField(
            model_name='area_model',
            name='STAFF',
        ),
        migrations.AddField(
            model_name='authority_model',
            name='AREA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AquaFlowApp.area_model'),
        ),
        migrations.AddField(
            model_name='authority_model',
            name='LOGIN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AquaFlowApp.login_model'),
        ),
        migrations.AddField(
            model_name='chat_model',
            name='FROMID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fromid', to='AquaFlowApp.login_model'),
        ),
        migrations.AddField(
            model_name='chat_model',
            name='TOID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AquaFlowApp.login_model'),
        ),
        migrations.AddField(
            model_name='staff_model',
            name='AREA',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AquaFlowApp.area_model'),
        ),
        migrations.AddField(
            model_name='staff_model',
            name='AUTHORITY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AquaFlowApp.authority_model'),
        ),
        migrations.AddField(
            model_name='staff_model',
            name='LOGIN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AquaFlowApp.login_model'),
        ),
        migrations.AddField(
            model_name='user_model',
            name='LOGIN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AquaFlowApp.login_model'),
        ),
        migrations.AlterField(
            model_name='application_model',
            name='USER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AquaFlowApp.user_model'),
        ),
        migrations.AlterField(
            model_name='assignedwork_model',
            name='STAFF',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AquaFlowApp.staff_model'),
        ),
        migrations.AlterField(
            model_name='bill_model',
            name='READING',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AquaFlowApp.reading_model'),
        ),
        migrations.AlterField(
            model_name='bill_model',
            name='USER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AquaFlowApp.user_model'),
        ),
        migrations.AlterField(
            model_name='complaints_model',
            name='USER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AquaFlowApp.user_model'),
        ),
        migrations.AlterField(
            model_name='feedback_model',
            name='USER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AquaFlowApp.user_model'),
        ),
        migrations.AlterField(
            model_name='reading_model',
            name='STAFF',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AquaFlowApp.staff_model'),
        ),
        migrations.AlterField(
            model_name='reading_model',
            name='USER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AquaFlowApp.user_model'),
        ),
        migrations.AlterField(
            model_name='report_model',
            name='STAFF',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AquaFlowApp.staff_model'),
        ),
    ]
