# Generated by Django 5.1.2 on 2024-11-16 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AquaFlowApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='application_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Application_no', models.IntegerField(blank=True, null=True)),
                ('Complaint_no', models.IntegerField(blank=True, null=True)),
                ('Status', models.CharField(blank=True, max_length=100, null=True)),
                ('Panchayath_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('Phone_no', models.IntegerField(blank=True, null=True)),
                ('Family_members', models.IntegerField(blank=True, null=True)),
                ('Adhar_no', models.IntegerField(blank=True, null=True)),
                ('Rationcard', models.CharField(blank=True, max_length=100, null=True)),
                ('Neighbourconsumer_no', models.IntegerField(blank=True, null=True)),
                ('Cast', models.CharField(blank=True, max_length=100, null=True)),
                ('Adhar_photo', models.FileField(blank=True, null=True, upload_to='photo/')),
                ('Rationcard_photo', models.FileField(blank=True, null=True, upload_to='photo/')),
                ('Ownershipcertificate_photo', models.FileField(blank=True, null=True, upload_to='photo/')),
            ],
        ),
        migrations.CreateModel(
            name='area_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='assignedwork_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.CharField(blank=True, max_length=100, null=True)),
                ('Work', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bill_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_amount', models.IntegerField(blank=True, null=True)),
                ('Consumer_no', models.CharField(blank=True, max_length=100, null=True)),
                ('Time', models.TimeField(blank=True, null=True)),
                ('Payment_status', models.CharField(blank=True, max_length=100, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Due_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='chat_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sender_loginid', models.CharField(blank=True, max_length=100, null=True)),
                ('Reciever_loginid', models.CharField(blank=True, max_length=100, null=True)),
                ('Time', models.TimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='complaints_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Send_feedback', models.CharField(blank=True, max_length=100, null=True)),
                ('Rating', models.CharField(blank=True, max_length=100, null=True)),
                ('Reply', models.FileField(blank=True, null=True, upload_to='')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='reading_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Consumer_no', models.CharField(blank=True, max_length=100, null=True)),
                ('Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Previous_reading', models.IntegerField(blank=True, null=True)),
                ('Current_reading', models.IntegerField(blank=True, null=True)),
                ('Total_usage', models.IntegerField(blank=True, null=True)),
                ('Fixed_charge', models.IntegerField(blank=True, null=True)),
                ('Advance', models.IntegerField(blank=True, null=True)),
                ('Prior_obligation', models.IntegerField(blank=True, null=True)),
                ('Fine', models.IntegerField(blank=True, null=True)),
                ('Total_amount', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='report_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Consumer_no', models.CharField(blank=True, max_length=100, null=True)),
                ('Complaint_no', models.CharField(blank=True, max_length=100, null=True)),
                ('Upload_photo', models.FileField(blank=True, null=True, upload_to='photo/')),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='time_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Area', models.CharField(blank=True, max_length=100, null=True)),
                ('Time', models.TimeField(blank=True, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Mid_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('Mail', models.CharField(blank=True, max_length=100, null=True)),
                ('Pincode', models.IntegerField(blank=True, null=True)),
                ('Address', models.CharField(blank=True, max_length=100, null=True)),
                ('Consumer_no', models.CharField(blank=True, max_length=100, null=True)),
                ('Profile', models.FileField(blank=True, null=True, upload_to='profile/')),
                ('Phone_no', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='authority_model',
            old_name='area',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='authority_model',
            old_name='name',
            new_name='Area',
        ),
        migrations.RenameField(
            model_name='authority_model',
            old_name='profile',
            new_name='Profile',
        ),
        migrations.RenameField(
            model_name='login_model',
            old_name='password',
            new_name='Password',
        ),
        migrations.RenameField(
            model_name='login_model',
            old_name='username',
            new_name='Username',
        ),
        migrations.RenameField(
            model_name='staff_model',
            old_name='area',
            new_name='Address',
        ),
        migrations.RenameField(
            model_name='staff_model',
            old_name='name',
            new_name='First_name',
        ),
        migrations.RemoveField(
            model_name='staff_model',
            name='profile',
        ),
        migrations.AddField(
            model_name='authority_model',
            name='First_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='authority_model',
            name='Last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='authority_model',
            name='Mail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='authority_model',
            name='Mid_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='authority_model',
            name='Panchayath_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='authority_model',
            name='Phone_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='authority_model',
            name='Pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff_model',
            name='AUTHORITY',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AquaFlowApp.authority_model'),
        ),
        migrations.AddField(
            model_name='staff_model',
            name='Last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff_model',
            name='Mail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff_model',
            name='Mid_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='staff_model',
            name='Phone_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff_model',
            name='Pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staff_model',
            name='Profile',
            field=models.FileField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
