# Generated by Django 5.1.2 on 2024-12-07 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AquaFlowApp', '0003_rename_adhar_photo_application_model_aadhaar_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority_model',
            name='Last_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
