# Generated by Django 5.1.2 on 2024-12-07 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AquaFlowApp', '0004_alter_authority_model_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority_model',
            name='Last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
