# Generated by Django 5.1.4 on 2025-01-11 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AquaFlowApp', '0005_alter_authority_model_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application_model',
            name='Mother_name',
        ),
        migrations.RemoveField(
            model_name='application_model',
            name='Status',
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='AquaFlowApp.login_model')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='AquaFlowApp.login_model')),
            ],
        ),
    ]
