# Generated by Django 5.1.4 on 2025-01-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AquaFlowApp', '0006_remove_application_model_mother_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints_model',
            name='complaint_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
