# Generated by Django 5.1.4 on 2025-01-20 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AquaFlowApp', '0007_complaints_model_complaint_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_model',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
