# Generated by Django 5.1.4 on 2025-01-20 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AquaFlowApp', '0008_alter_time_model_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_model',
            name='Area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AquaFlowApp.area_model'),
        ),
    ]
