# Generated by Django 5.1.4 on 2025-02-15 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AquaFlowApp', '0009_user_model_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time_model',
            old_name='Time',
            new_name='evening_Time',
        ),
        migrations.RemoveField(
            model_name='time_model',
            name='Area',
        ),
        migrations.AddField(
            model_name='time_model',
            name='morning_Time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
