# Generated by Django 5.1.4 on 2025-02-15 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AquaFlowApp', '0010_rename_time_time_model_evening_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application_model',
            name='Status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
