# Generated by Django 5.1.4 on 2025-02-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AquaFlowApp', '0011_application_model_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application_model',
            name='Status',
            field=models.CharField(blank=True, default='pending', max_length=100, null=True),
        ),
    ]
