# Generated by Django 5.1.4 on 2025-03-01 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AquaFlowApp', '0012_alter_application_model_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='login_model',
            name='Otp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
