# Generated by Django 5.1.4 on 2025-03-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AquaFlowApp', '0013_login_model_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_model',
            name='description',
            field=models.CharField(blank=True, default='morining and evening time', max_length=100, null=True),
        ),
    ]
