# Generated by Django 5.1.4 on 2025-03-01 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AquaFlowApp', '0014_alter_time_model_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints_model',
            name='assignedstaff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AquaFlowApp.staff_model'),
        ),
    ]
