# Generated by Django 5.1.4 on 2025-03-08 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AquaFlowApp', '0015_complaints_model_assignedstaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedwork_model',
            name='USER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AquaFlowApp.user_model'),
        ),
    ]
