# Generated by Django 5.1.4 on 2025-03-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AquaFlowApp', '0016_assignedwork_model_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading_model',
            name='Previous_reading',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
