# Generated by Django 5.1.4 on 2025-03-09 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AquaFlowApp', '0017_reading_model_previous_reading'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback_model',
            name='COMPLAINT',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AquaFlowApp.complaints_model'),
        ),
    ]
